### ISSUE TITLE
About part segmentation

### ISSUE THREAD

**Issue by qq456cvb** [nini-lxz/Rotation-Invariant-Point-Cloud-Analysis#1]
Thanks for sharing your code on rotation invariant classification. I doubt if it is possible to release the code and pretrained model for ShapeNet part segmentation?

**Comment by nini-lxz** [comment]
Hi, Thanks for your attention! I have shared the segmentation code for your reference.

**Comment by qq456cvb** [comment]
Thank you for updating! I will try the code.
